#!/usr/bin/env bash
# Get and set secrets using MacOS keychain.

set -e

PROG="$(basename $0)"
VERSION="$PROG %VERSION%"
SERVICE_NAME="SECRET_CLI"

CMD=$1
NAME=$2
SECRET=$3

function main() {

  case "$CMD" in
    "get")
      assert $NAME
      get_secret
      ;;
    "set")
      assert $NAME
      assert $SECRET
      set_secret
      ;;
    "delete")
      assert $NAME
      delete_secret
      ;;
    "version")
      echo $VERSION
      ;;
    *)
      usage_and_exit
      ;;
  esac
}


function usage_and_exit() {
  echo "Usage: "
  echo "  $PROG get <name>           Get secret with given name."
  echo "  $PROG set <name> <value>   Set secret with given name and value."
  echo "  $PROG delete <name>        Delete secret with given name."
  echo "  $PROG version              Print program version."
  exit 1
}

function get_secret() {
  set +e
  output="$(/usr/bin/security 2>&1 > /dev/null find-generic-password -s $SERVICE_NAME -a $NAME -g)"
  set -e

  if (echo $output | grep security); then
    exit 1
  fi

  echo -n "$output" |
    grep password |
    sed -E 's/^password: "(.+)"$/\1/'
}

function set_secret() {
  /usr/bin/security add-generic-password -s $SERVICE_NAME -a $NAME -w $SECRET -U -j "Added by $0"
}

function delete_secret() {
  /usr/bin/security 2>&1 >/dev/null delete-generic-password -s $SERVICE_NAME -a $NAME
}

function assert() {
  if [[ -z "$1" ]]; then
    usage_and_exit
  fi
}

main
